### ISSUE TITLE
重启后失效 

### ISSUE THREAD

**Issue by tangjinzhou** [cydiacen/xb-frontend-extension#1]
![image](https://user-images.githubusercontent.com/6937879/71227157-42cb5d80-2319-11ea-8529-6c84d4860348.png)

**Comment by cydiacen** [comment]
问题原因:
经测试 是由于`json`文件不会触发插件的初始化事件,所以一大堆的功能没用,打开其他文件的时候会重新触发插件的启动,可以临时解决下这个问题.
解决方案:
已将json文件添加到启动文件类型的列表,不过治标不治本,后续会研究其他方案,保证插件的正常初始化.
commit:
https://github.com/cydiacen/xb-frontend-extension/pull/2/commits/acffdea567a53f27d5db5ed0905c64d64419362c
